import { Box, Typography, Link } from '@mui/material';

function Footer() {
  return (
    <Box
      sx={{
        height: '100%',
        width: '100%',
        color: '#8F938A',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
      }}
    >
      <Typography
        sx={{ color: '#a28f9d', fontSize: '0.8rem', fontWeight: 'bold', marginLeft: '20px' }}
      >
        ©2022. App developed as an exercise of the Program Starter 5 Ed. on React. What do I eat
        title generated by{' '}
        <Link
          href="https://awesome-title-generator.herokuapp.com/"
          target="_blank"
          sx={{ textDecoration: 'none', color: '#6fffe9' }}
        >
          {' '}
          Awesome Title app{' '}
        </Link>{' '}
        .
      </Typography>
      <Link href="https://www.growdev.com.br/" target="_blank" sx={{ marginRight: '20px' }}>
        <img
          src="https://www.growdev.com.br/assets/images/logo-dark.png"
          alt="growdev"
          style={{ height: '3rem' }}
        />
      </Link>
    </Box>
  );
}

export default Footer;
