import { Box, Typography, Link } from '@mui/material';

function Footer() {
  return (
    <Box
      sx={{
        height: '7%',
        width: '95%',
        color: '#8F938A',
        display: 'flex',
        justifyContent: 'space-around',
        alignItems: 'center',
      }}
    >
      <Typography
        sx={{ color: '#8F938A', fontSize: '1rem', fontWeight: 'bold', marginLeft: '10px' }}
      >
        ©2022. App developed as an exercise of the Program Starter 5 Ed. on React. Phone List title
        generated by{' '}
        <Link
          href="https://awesome-title-generator.herokuapp.com/"
          target="_blank"
          sx={{ textDecoration: 'none', color: '#158c3f' }}
        >
          {' '}
          Awesome Title app{' '}
        </Link>{' '}
        .
      </Typography>
      <Link href="https://www.growdev.com.br/" target="_blank">
        <img
          src="https://www.growdev.com.br/assets/images/logo-dark.png"
          alt="growdev"
          style={{ height: '3rem' }}
        />
      </Link>
    </Box>
  );
}

export default Footer;
